package com.example.safedistance.utils

enum class Constants {
    ACTION_CLOSE_ALL_ACTIVITIES,
    ACTION_CLOSE_ALL_SERVICES,
    ACTION_DISTANCE,
    ACTION_START_CAMERA,
    ACTION_STOP_CAMERA,
    ACTION_START_MEASURE,
    ACTION_STOP_MEASURE,
    ACTION_START_VIBRATION,
    ACTION_STOP_VIBRATION,

    VALUE_DISTANCE,
    VALUE_TITLE,
    VALUE_MESSAGE,

    ACTION,
    DATA
}